#!/usr/bin/env python
import argparse as apa
def loadConfig(config):
    print("Load config from: {}".format(config))
def setTheme(theme):
    print("Set theme: {}".format(theme))
def main():
    parser = apa.ArgumentParser(prog="convert")
    parser.add_argument("-c", "--config", required=False, default="config.ini")
    parser.add_argument("-t", "--theme", required=False, default="default.theme")
    parser.add_argument("-f") # Accept Jupyter runtime option
    args = parser.parse_args()
    loadConfig(args.config)
    setTheme(args.theme)

if __name__ == "__main__":
    main()